- Casks/liteide.rb
> change to qt5 from qt4

- Casks/bluefish.rb
add bluefish.rb 2.2.8
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*
After making all changes to the cask:
[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
> Add Bluefish 2.2.8

- Casks/grids.rb
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*
After making all changes to the cask:
[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
> Add Grids 4.4

- Casks/heimatdefender-rebellion.rb
After making all changes to a cask, verify:
> Add HeimatDefender.app v1.1

- Casks/brooklite.rb
After making all changes to a cask, verify:
> Add brooklite

- Casks/flutter.rb
After making all changes to a cask, verify:
> Update flutter from 2.0.4 to 2.0.5

- Casks/manila.rb
After making all changes to a cask, verify:
> Add Manila 1.0.1

- Casks/wezterm.rb
https://wezfurlong.org/wezterm/changelog.html#20220624-141144-bd1b7c5d
> Update WezTerm from 20220408-101518-b908e2dd to 20220624-141144-bd1b7c5d

- Casks/y/yass.rb
> yass 1.9.3 (new cask)

- Casks/y/yass.rb
> yass 1.9.4

- Casks/y/yass.rb
> yass 1.9.5

- Casks/y/yass.rb
> yass 1.10.0

- Casks/y/yass.rb
> yass 1.10.1

- Casks/y/yass.rb
> yass 1.10.2

- Casks/y/yass.rb
> yass: 1.10.3

- Casks/y/yass.rb
> yass 1.10.4

- Casks/y/yass.rb
> yass: 1.11.0

- Casks/y/yass.rb
> yass: 1.11.1

- Casks/y/yass.rb
> yass: 1.11.3

- Casks/y/yass.rb
> yass: 1.11.4

- Casks/y/yass.rb
> yass: 1.12.1

- Casks/y/yass.rb
> yass: 1.12.3

- Casks/y/yass.rb
> yass: 1.13.0

- Casks/y/yass.rb
> yass: 1.13.1

- Casks/y/yass.rb
> yass: 1.13.2

- Casks/y/yass.rb
> yass 1.14.0

- Casks/font/font-s/font-suit.rb
> font-suit 2.0.5 (new cask)
